name: flutter_gif
description: gif image widget help to control gif progress,speed,repeat frames .
version: 0.0.6
homepage: https://github.com/saytoonz/flutter_gif

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
